README.md
hass_opensprinkler/__init__.py
hass_opensprinkler/binary_sensor.py
hass_opensprinkler/sensor.py

This adds several additional binary sensors for the rain sesnor, rain
delay and whether operation is enabled in general, as well as a sensor
for the Rain Delay Stop Time.
Also features a minor bit of refactoring for querying controller
variables to reduce code duplication when hitting the `/jc` endpoint as
per the API (see
https://openthings.freshdesk.com/support/solutions/articles/5000716363-os-api-documents)

Add rain, rain delay and operation sensors

---

hass_opensprinkler/__init__.py

Adding response encoding to resolve response treated as ISO-8859-1 (default) when it should be UTF 8 as detected by the response
response.encoding = response.apparent_encoding detects character encoding. Opensprinkler API doesn't correctly set the charset header Content-Type: text/html; charset=utf-8

Adding response encoding

---

README.md
custom_components/opensprinkler/__init__.py
custom_components/opensprinkler/const.py
custom_components/opensprinkler/sensor.py
custom_components/opensprinkler/services.yaml
custom_components/opensprinkler/switch.py

Closes #59 
Closes #60 
To test:
Developer Tools -> Services
Services available: `opensprinkler.run_program`, `opensprinkler.run_station`, `opensprinkler.stop_station`

New: services to run programs and run/stop stations

---

custom_components/opensprinkler/manifest.json

Fixes: #89 , all timestamps should now be in UTC
Reference: https://github.com/vinteo/py-opensprinkler/pull/42

chore: update pyopensprinkler to 0.6.7

---

custom_components/opensprinkler/__init__.py
custom_components/opensprinkler/manifest.json

Provides for more user friendly `device_info` as below. **Note: Requires py-opensprinkler [PR47](https://github.com/vinteo/py-opensprinkler/pull/47)**

Friendly device info

---

custom_components/opensprinkler/binary_sensor.py
custom_components/opensprinkler/sensor.py
custom_components/opensprinkler/switch.py

Re-assign controller attributes to more relevant entities:
- `last_weather...` attributes assigned to `water_level` entity
- `last_run...` attributes assigned to `last_run` entity
- `sensor_X_enabled` assigned to `sensor_X_active` entity
Removed firmware/hardware attributes from controller as already present in `device_info`

Re-assign controller attributes to relevant entities

---

custom_components/opensprinkler/switch.py

This PR exposes the controller's firmware version as part of the device attributes of the controller operation switch; useful for inclusion within templates, automations and UI.

feat: expose firmware version as device attribute

---

custom_components/opensprinkler/manifest.json
hacs.json

Only compatible with HA 2023.3.0b0 and up!
Closes #210

Bump pyopensprinkler to 0.7.6

---

.gitignore
custom_components/opensprinkler/__init__.py
custom_components/opensprinkler/number.py

New feature to support viewing and editing program station durations using the Number entity.
I followed your pattern for creating entity types, and created an OpenSprinklerNumber class in __init__.py; but as the Number Entity documentation specified to use "native_value" for the number's value, I didn't see the need for creating a "state" property here, so I left it empty, and just return native_value in number.py. Perhaps you could explain why you decided to use this extra class to return the state in other entities, and let me know how you want to handle this going forward. It will also be an issue in future PRs.
Also, I chose to support minutes instead of seconds. While providing seconds gives the user more control, I don't see any real value in running a zone for under a minute. I …

feat: Station durations

---

custom_components/opensprinkler/__init__.py
custom_components/opensprinkler/time.py

New feature to support program start time. For consistency with durations, rounded to nearest minute.
Uses the [Time ](https://www.home-assistant.io/integrations/time/)integration.
EXAMPLE:

feat: edit-start-time

---

custom_components/opensprinkler/services.yaml
custom_components/opensprinkler/translations/en.json

Move service name and description strings to translations folder to support new "Translated services" feature in 2023.8.
Not sure that it's compatible with earlier versions of HA, but I believe the settings will stick until overridden, so probably only an issue for new installations of the integration.
Required change to satisfy "hassfest" Action.

Move name and description to translations

---

custom_components/opensprinkler/config_flow.py
custom_components/opensprinkler/strings.json
custom_components/opensprinkler/translations/en.json

Cleanup of translations and minor adjustments. Looks worse than it is because strings.json was overwritten (and can be ignored).
1. While I couldn't find a definitive reference in the "official" docs, the consensus seems to be that strings.json should be exactly the same as the primary language in the translations folder, en.json. This is probably for backward compatibility, and the duplicate hopefully can eventually go away. Have copied en.json to strings.json.
2. Error strings do not get translated in non-core integrations. Converted them to the text in core: homeassistant/strings.json
3. Slightly out of scope, but errors for badly formatted URLs during config flow were falling thru to the generic Exception and getting displayed as "Unexpected exception". Now trap the aiohttp InvalidURL …

chore-cleanup-translations

---

custom_components/opensprinkler/__init__.py

Addresses 2nd part of "Fix hassfest errors #237", the Warning:
[CONFIG_SCHEMA] Integrations which implement 'async_setup' or 'setup' must define either 'CONFIG_SCHEMA', 'PLATFORM_SCHEMA' or 'PLATFORM_SCHEMA_BASE'. If the integration has no configuration parameters, can only be set up from platforms or can only be set up from config entries, one of the helpers cv.empty_config_schema, cv.platform_only_config_schema or cv.config_entry_only_config_schema can be used.
May possibly address "Issue upgrading to Home Assistant Core 2023.8.0 #238". I don't use HACS, so don't know if it's still stuck at v1.1.15, but if it is, this could possibly be the cause, if the Warning above is the result of a new rule. Not sure when the rule was introduced or if Warnings prevent upgrades. Have no idea how that …

chore-eliminate-hassfest-warning

---

README.md

The default port for OpenSprinkler is "80", though the `README.md` shows "8080". This is the case at least as far back as the earliest available User Manual, for Firmware 2.1.6.
From the latest Firmware 2.2.0 manual:
> Next, open a browser and type in the
> URL http://os-ip (e.g. http://192.168.1.122). In case you have set a custom HTTP port number
> (other than the default 80), include the port number in the URL as well.

fix-docs-port-default

---

custom_components/opensprinkler/sensor.py

Disables `sensor.opensprinkler_current_time` by default. Addresses Issue #249.
Was planning to remove this entity and replace with a service, but now that it's released I think this is the way to go. Can still add a service later.
We don't need a constant update of the current time, but I have found it to wander in the past unexpectedly, so it's nice to have a way to check periodically.

fix-disable-current-time-by-default

---

custom_components/opensprinkler/manifest.json
custom_components/opensprinkler/number.py

Feature to complete support for `Additional Start Times`. Requires `py-opensprinkler v0.7.9`.
By using Conditional Cards, users can display the appropriate controls, depending on the `Start Time Type`:
Because data in the fields start1-3 is stored differently depending on the `Start Time Type`, these fields are cleared by `py-opensprinkler` whenever the type is changed.
The new entities for repeat count and interval are created `Disabled` to reduce entity bloat for those who do not use `Additional Start Times`.

feat-support-repeating-start-times

---

custom_components/opensprinkler/manifest.json
custom_components/opensprinkler/number.py
custom_components/opensprinkler/select.py
custom_components/opensprinkler/switch.py

Fully support `Interval` vs. `Weekly` scheduling. Creates a new `switch` entity for each day of the week for each program. Entities are disabled by default to avoid entity bloat for those not using `Weekly` scheduling. Depends on `py-opensprinkler` PR https://github.com/vinteo/py-opensprinkler/pull/88.
This completes support for all features available on the older (pre `Date Range`) version of the `OpenSprinkler` `Edit Programs` web page.
A conditional card can be used to display only appropriate controls, depending on the `Program Type` currently selected, as shown here:

feat-support-weekly-schedule

---

README.md

Added the new services and updated the README version.
The HACS action badge still says failing, but the action is passing. Doing a quick search, it seems like sometimes github can show this because of an old failed run? There is one failure for the master branch in the history, but it's so old the logfiles aren't kept anymore. Should we just delete that run and see if it fixes the badge?

Add new services to README and updated version references.

---

custom_components/opensprinkler/__init__.py

In Home Assistant `2024.2.1` this service is always erroring with:
```
Failed to call service opensprinkler/run. 'list' object has no attribute 'get'
```
The stacktrace for this error is below:
```
2024-02-10 12:46:23.684 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [<REDACTED>] 'list' object has no attribute 'get'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
return await …
```

Fix broken services in HA `2024.2.1`

---

custom_components/opensprinkler/services.yaml
custom_components/opensprinkler/switch.py

Show only **valid** entities in the UI when configuring services. Fixes Issue #280 .
Services that affect the controller will list `switch.<controller>_enabled`.
Services that affect programs will list all `switch.<program>_program_enabled` entities.
Services that affect stations will list all `switch.<station>_station_enabled` entities.
Services that affect more than one of the above will list multiple types of entities.
The UI will not list values under `Choose area` or `Choose device`, as these would then select inappropriate entities for the service.
While other legitimate entities such as `sensor.<station>_station_status` could have also been listed, they provide no additional value and were left out to prevent clutter. However, nothing prevents a user from using these in `YAML`, so …

Feat show valid service entities

---

custom_components/opensprinkler/__init__.py

This resolves Issue #284, which pointed out that one of the formats for creating template switches used in the examples no longer works.
Consider this snippet:
```
run_seconds:
0: 60
1: 60
2: 60
3: 60
4: 60
5: 60
```
If this is called as part of `opensprinkler.run` from `Developer tools > Services`, the keys are converted to strings, which is what the code expects. However, if it is part of a template switch, they arrive as integers, which `dict.get()` interprets as a lookup failure and returns `None`. Ultimately, the run durations are set to 0.
This PR attempts to find both int and str keys. If you know of a better way to cover both cases than to use the `default` parameter of `dict.get()`, please speak up.

fix: allow run_seconds to use int or str as keys

---

custom_components/opensprinkler/__init__.py

Replace calls to `hass.config_entries.async_forward_entry_setup` with `await hass.config_entries.async_forward_entry_setups`.
Resolves #295.

async_forward_entry_setup is deprecated

---

custom_components/opensprinkler/__init__.py

Fixes https://github.com/vinteo/hass-opensprinkler/issues/293
After investigating, i think the problem isn't really the `TIMEOUT` nor `SCAN_INTERVAL`, as this is something HAs built-in `DataUpdateCoordinator` should handle.
Instead, the problem is error management. We do get an error, but we ignore it!
Instead, we rely on `controller._state`, but this doesn't get cleared when an error occurs.
This PR fixes the problem by propagating the error if we get one.

Fix going unavailable

---

custom_components/opensprinkler/__init__.py
custom_components/opensprinkler/config_flow.py
custom_components/opensprinkler/strings.json
custom_components/opensprinkler/translations/de.json
custom_components/opensprinkler/translations/en.json
custom_components/opensprinkler/translations/sk.json

With https://github.com/vinteo/hass-opensprinkler/pull/298 merged, we should also add support for the reauthentication flow.
This PR also simplifies exception management on initial poll, by using HA's built-in `async_config_entry_first_refresh()` function.
It will automatically raise `ConfigEntryNotReady` when an error occurs. This allows us to remove a big `try:` block.

Add support for reauth flow

---

custom_components/opensprinkler/__init__.py

Changes call to entity_service_call to pass the hass as the first parameter and imports the proper package.

Addresses issue #304 deprecated_has_helpers_service

---

README.md
custom_components/opensprinkler/__init__.py
custom_components/opensprinkler/const.py
custom_components/opensprinkler/services.yaml
custom_components/opensprinkler/strings.json
custom_components/opensprinkler/translations/en.json

This is a continuation of an earlier effort to simplify and clarify action (service) calling. That effort limited the available entities presented by the UI to only those appropriate to the action. This PR was inspired by Issue #313 and is intended to reduce the available selection of parameters available in the UI to the `run` action depending on the use case.
It has become clear that the only way to effectively do this was to split the `run` action into multiple actions, one for each type of target entity. This is due to the fact that each entity type (controller, station, and program) takes a different set of parameters: `run_seconds` and `continue_running_stations`, only `run_seconds`, and no parameters, respectively.
Therefore, I have added these new actions:
- `run_once`
- …

Split run services by target type

---

custom_components/opensprinkler/binary_sensor.py
custom_components/opensprinkler/number.py
custom_components/opensprinkler/select.py
custom_components/opensprinkler/sensor.py
custom_components/opensprinkler/switch.py
custom_components/opensprinkler/text.py
custom_components/opensprinkler/time.py

When I first added this integration I was a bit overwhelmed with the sheer number of entities that were added to my auto-generated default dashboard. This PR moves many of them to the config and diagnostic entity categories, as well as assigning some more device classes.
See also Integration Quality Rules:
- [Entities are assigned an appropriate EntityCategory](https://developers.home-assistant.io/docs/core/integration-quality-scale/rules/entity-category/)
- [Entities use device classes where possible](https://developers.home-assistant.io/docs/core/integration-quality-scale/rules/entity-device-class/)

Assign entity categories and device classes

---

custom_components/opensprinkler/manifest.json
custom_components/opensprinkler/number.py

Chrome and the Companion App hang when displaying the integration page for OpenSprinkler. In my case it appears that the `native_max_value` for `ProgramStartingInDaysNumber` was being calculated as -1, or less than the `native_min_value` of 0 for one of my inactive programs.
Resolves #339.
The version number in the manifest has been bumped and a release is necessary.

Fix: Integration page hangs after HA 2025.10
