vinteo/hass-opensprinkler

- README.md
Relates to: https://github.com/vinteo/hass-opensprinkler/issues/1
> Update: Make it clearer password should be MD5

- custom_components/hass_opensprinkler/__init__.py
- custom_components/hass_opensprinkler/binary_sensor.py
Added support for Open Sprinkler version 2.19 which added an additional rain sensor, and changed the REST commands to access both sensors.
> Add support for OS 2.19

- README.md
This helps explain a few more details that I tripped over, as well as providing a few more pointers to people not as familiar with Home Assistant yet.
Fixes #44
> Update Configuration section of README.md

- custom_components/hass_opensprinkler/__init__.py
- custom_components/hass_opensprinkler/switch.py
> New: switch to enable/disable opensprinkler controller

- custom_components/hass_opensprinkler/__init__.py
- custom_components/hass_opensprinkler/binary_sensor.py
- custom_components/hass_opensprinkler/switch.py
> New: binary sensors and switches for program operation

- custom_components/hass_opensprinkler/binary_sensor.py
- custom_components/hass_opensprinkler/sensor.py
- custom_components/hass_opensprinkler/switch.py
fixes: https://github.com/vinteo/hass-opensprinkler/issues/61
> Update: replace deprecated entities

- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/sensor.py
- custom_components/opensprinkler/switch.py
> Update: controller and program switches

- custom_components/opensprinkler/switch.py
Scoping the controller switch with `operation` as we'll likely have other controller level switches.
> Station switches

- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/binary_sensor.py
- custom_components/opensprinkler/sensor.py
- custom_components/opensprinkler/switch.py
Initial stab at icons.
Closes: #72
> icons, minor state attrs adjustments, None when 0 for timestamp

- custom_components/opensprinkler/binary_sensor.py
- custom_components/opensprinkler/sensor.py
> new sensors for the controller sensors

- README.md
- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/binary_sensor.py
- custom_components/opensprinkler/sensor.py
- custom_components/opensprinkler/services.yaml
- custom_components/opensprinkler/switch.py
> feat: stop all station service

- README.md
- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/binary_sensor.py
- custom_components/opensprinkler/const.py
- custom_components/opensprinkler/sensor.py
- custom_components/opensprinkler/services.yaml
- custom_components/opensprinkler/switch.py
fixes: #78 
- added service to run once program on controller entities
- made service call examples more explicit
- added in station switch example using template switch and input number
> feat: service to run once program

- custom_components/opensprinkler/__init__.py
> refactor: move entity attributes to specific classes

- README.md
- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/binary_sensor.py
- custom_components/opensprinkler/const.py
- custom_components/opensprinkler/sensor.py
- custom_components/opensprinkler/services.yaml
- custom_components/opensprinkler/switch.py
> feat: continue_running_stations flag for run once program service

- README.md
There was a question asked about the options due to some confusion in the HA community forums
> chore: be more detailed for integration options in readme

- custom_components/opensprinkler/manifest.json
> chore: update pyopensprinkler to 0.6.10

- custom_components/opensprinkler/binary_sensor.py
Icons are to be removed in 0.115
> fix: update deprecating icons

- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/config_flow.py
- custom_components/opensprinkler/manifest.json
- custom_components/opensprinkler/switch.py
Install version ~~`v1.1.0-beta.1`~~ ~~`1.1.0-beta.2`~~ ~~`1.1.0-beta.3`~~ `1.1.0-beta.4` from HACS to test this branch
Uses beta release (~~`0.7.0b1`~~ ~~`0.7.0b2`~~ `0.7.0b3`) of pyopensprinkler: https://github.com/vinteo/py-opensprinkler/pull/50
> feat: async pyopensprinkler

- custom_components/opensprinkler/__init__.py
Fixes: https://github.com/vinteo/hass-opensprinkler/issues/138
> feat: check for initial load success

- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/config_flow.py
- custom_components/opensprinkler/const.py
- custom_components/opensprinkler/manifest.json
- custom_components/opensprinkler/sensor.py
- custom_components/opensprinkler/switch.py
Includes security fixes for `aiohttp`
> chore: upgrade pyopensprinkler to 0.7.1

- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/binary_sensor.py
- custom_components/opensprinkler/manifest.json
- custom_components/opensprinkler/sensor.py
- custom_components/opensprinkler/switch.py
Fixes #126, closes https://github.com/vinteo/hass-opensprinkler/pull/127
> fix: register services differently to fix broken services

- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/binary_sensor.py
- custom_components/opensprinkler/manifest.json
- custom_components/opensprinkler/sensor.py
- custom_components/opensprinkler/switch.py
> fix: replace deprecated device_state_attributes

- .github/workflows/linting.yml
- README.md
- custom_components/opensprinkler/manifest.json
> chore: pyopensprinkler 0.7.2

- README.md
- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/const.py
- custom_components/opensprinkler/services.yaml
- hacs.json
Adds a new service that can set the water level for an OpenSprinkler in percent.
Fixes https://github.com/vinteo/hass-opensprinkler/issues/101
> New Service: Set water level

- README.md
- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/config_flow.py
- custom_components/opensprinkler/manifest.json
Fixes: https://github.com/vinteo/py-opensprinkler/issues/67
> chore: pyopensprinkler-0.7.4

- custom_components/opensprinkler/__init__.py
Fixes: https://github.com/vinteo/hass-opensprinkler/pull/188
> Update: add integration configuration url

- custom_components/opensprinkler/const.py
- custom_components/opensprinkler/services.yaml
Closes: https://github.com/vinteo/hass-opensprinkler/issues/187
> Increase max water level to 250%

- custom_components/opensprinkler/sensor.py
> Update: replace deprecated device class constants

- custom_components/opensprinkler/manifest.json
To pass hassfest github action
> chore: order manifest alphabetically

- .github/workflows/hacs.yml
- .github/workflows/linting.yml
- README.md
- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/const.py
- custom_components/opensprinkler/services.yaml
New service to reboot OpenSprinkler controller.
> feat: Add reboot service

- custom_components/opensprinkler/switch.py
New switch to control the "Use Weather Adjustment" feature for a program.
> feature-use-weather-switch

- custom_components/opensprinkler/manifest.json
- hacs.json
> chore: pyopensprinkler 0.7.7

- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/text.py
New feature to allow editing of program names. Uses the Text entity type.
> feat: edit program name

- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/select.py
New feature to allow selection of odd-even restriction. Uses Select entity type.
> Feature: Select odd-even restriction

- custom_components/opensprinkler/select.py
New feature to support selecting Program Type ("Weekday", "Interval") and Additional Start Times ("Repeating", "Fixed").
> Add remaining selects

- custom_components/opensprinkler/number.py
New feature to view/edit **Interval Days** and **Starting In** Days.
I struggled a bit with the "mode" property. I originally had it set to "box" because that's what I prefer, but the docs suggest setting it to "auto", which seems to give the same result as "slider", the default. The HA UI has little to no support for adjusting this that I can find. However, I discovered that the Mushroom Number card has support for setting this to "Slider" or "Buttons" (similar to "box" but without ability to type a value). So I pulled these values out of the Entities card I'm using on my panel and tried the Mushroom approach, which looks like it will work for me. 
Note that this will affect the Station Durations as well. The are set to "auto" currently.
Thoughts? Do you know of any other cards that …
> feat: Edit Interval, Starting In Days

- custom_components/opensprinkler/sensor.py
Feature to retrieve the current date/time from the controller. This can be useful for detecting a time shift in the controller.
> feat-get-controller-current-time

- custom_components/opensprinkler/translations/de.json
Added germant translation for this integration
> Added german translation

- custom_components/opensprinkler/manifest.json
- hacs.json
> chore: opensprinkler 0.7.8, version 1.2.3

- custom_components/opensprinkler/__init__.py
- custom_components/opensprinkler/binary_sensor.py
- custom_components/opensprinkler/const.py
- custom_components/opensprinkler/manifest.json
- custom_components/opensprinkler/sensor.py
- custom_components/opensprinkler/services.yaml
- custom_components/opensprinkler/strings.json
- custom_components/opensprinkler/translations/en.json
Per #218, hopefully better showers for all now :)
I've taken the liberty of incrementing the minor version number, but I'm not sure if that's appropriate or should happen later somehow. Apologies if I got it wrong.
> Control pause

- custom_components/opensprinkler/manifest.json
- custom_components/opensprinkler/sensor.py
> Suppress exception if pause is not supported by sprinkler.
